spring:
  application:
    name: "CheckoutService"
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:postgresql://localhost:5434/checkoutDB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    listener:
      direct:
        default-requeue-rejected: false
      type: direct
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8084/eureka/